config/routes.rb
require 'sidekiq/web'

SwiftIntro::Application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect("/")
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'users#show'
  
  resources :users, except: [:index] do
    get 'matches/prior_matches', to: 'matches#prior_matches'
    put 'matches/:id/send_potential_match_email', to: 'matches#send_potential_match_email', as: 'send_potential_match_email'
    resources :matches do
      resources :messages, only: [:create]
    end
    get 'messages/inbox', to: 'messages#inbox', as: 'messages_inbox'
    get 'messages/sent', to: 'messages#sent', as: 'messages_sent'
    post 'messages/send_message', to: 'messages#send_message', as: 'send_message'
  end

  mount Sidekiq::Web, at: '/admins/sidekiq'

  get 'admins/requests'
  get 'admins/metrics'
  get 'admins/queue'
  get 'admins/:id/past_matches', to: 'admins#past_matches', as: 'admins_past_matches'

  get 'users/:id/invite', to: 'users#invite', as: 'user_invite'
  get 'users/:id/premium', to: 'users#premium', as: 'user_premium'
  get 'users/:id/settings', to: 'users#settings', as: 'user_settings'
  post 'users/:id/delete_account', to: 'users#delete_account', as: 'user_delete_account'

  resources :admins, only: [:index, :show]
  resources :dashboard, only: [:index]

  get '/contact', to: 'dashboard#contact', as: 'contact'
  get '/faq', to: 'dashboard#faq', as: 'faq'
  get '/privacy', to: 'dashboard#privacy', as: 'privacy'

  get '/terms', to: 'dashboard#terms', as: 'terms'

  get '/:ref', to: 'dashboard#index'
end

app/views/admins/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <th>Users Requiring an Intro</th>
      <th>Potential Intros</th>
      <th># of Intros to Date</th>
      <th>City</th>
    </thead>
    <tbody>
      <% @eligible_users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= link_to 'Potential Intros', admin_path(user) %></td>
          <td><%= user.matches.count %> </td>
          <td><%= user.location.area %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/matches.html.erb
<div class="container">
  <h2>Match Metrics:</h2>

  <p>All Users: <%= @all_users_count %></p>
  <p>All Matches: <%= @all_matches.count %></p>
  <p>Both Agree to Meet: <%= @successful_matches_count %></p>
  <p>Success Rate: <%= (@successful_matches_count.to_f / @all_matches.count.to_f) * 100 %>%</p>

  <p>First User Agrees to Meet: <%= @first_user_yes_count %></p>
  <p>Second User Agrees to Meet: <%= @second_user_yes_count %></p>
  
  <p>First User Says No: <%= @first_user_no_count %></p>
  <p>Second User Says No: <%= @second_user_no_count %></p>
  <p>Reference Count: <%= @reference_count %></p>
  
</div>

app/views/admins/metrics.html.erb
<div class="container">
  <h2>Metrics:</h2>

  <p>All Users: <%= @all_users_count %></p>
  <p>Active Users: <%= @active_users_count %></p>
  <p>All Matches: <%= @all_matches.count %></p>
  <p>Both Agree to Meet: <%= @successful_matches_count %></p>
  <p>Success Rate: <%= ((@successful_matches_count.to_f / @all_matches.count.to_f) * 100).round(2) %>%</p>

  <p>First User Agrees to Meet: <%= @first_user_yes_count %></p>
  <p>Second User Agrees to Meet: <%= @second_user_yes_count %></p>
  
  <p>First User Says No: <%= @first_user_no_count %></p>
  <p>Second User Says No: <%= @second_user_no_count %></p>
  <p>Reference Count: <%= @reference_count %></p>
  
</div>

app/views/admins/past_matches.html.erb
<div class="container">
  <table class="table">
    <thead>
      <th>Past Match</th>
      <th>Headline</th>
      <th>Intro's Response</th>
      <th><%= @user.first_name %>'s Response</th>
    </thead>
    <tbody>
      <% @user.matches.each do |past_match| %>
        <% if past_match.first_user_id == @user.id %>
          <tr>
            <td><%= link_to past_match.second_user.name, user_path(past_match.second_user.id) %></td>
            <td><%= past_match.second_user.headline %></td>
            <td><%= past_match.second_user_status %></td>
            <td><%= past_match.first_user_status %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to past_match.first_user.name, user_path(past_match.first_user.id) %></td>
            <td><%= past_match.first_user.headline %></td>
            <td><%= past_match.first_user_status %></td>
            <td><%= past_match.second_user_status %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/queue.html.erb
<div class="container">
  <table class="table">
    <thead>
      <th>First User</th>
      <th>Second User</th>
      <th>City</th>
      <th></th>
    </thead>
    <tbody>
      <% @matches.each do |match| %>
          <tr>
            <td><%= link_to match.first_user.name, user_path(match.first_user.id) %></td>
            <td><%= link_to match.second_user.name, user_path(match.second_user.id) %></td>
            <td><%= match.first_user.location.area %></td>
            <td><%= button_to "Send Emails", user_send_potential_match_email_path(match.first_user.id, match.id), method: 'put', class: 'btn btn-primary' %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/requests.html.erb
<div class="container">
  <table class="table">
    <thead>
      <th>User requesting invite</th>
      <th>City</th>
      <th>Initial signup</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.location.area %></td>
          <td><%= link_to user.created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%B %e, %l:%M %p PST') %></td>
          <td><%= button_to "Approve", user_path(user, approved: "Yes"), method: 'put', class: 'btn btn-success' %> </td>
          <td><%= button_to "Reject", user_path(user, approved: "No"), method: 'put', class: 'btn btn-danger' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/show.html.erb
<div class="container">
  <h5>Potential intros for <%= link_to @user.name, user_path(@user) %> Score: <%= @user.score %></h5>
  <h5><%= link_to 'Past Intros', admins_past_matches_path(@user) %> (<%= @user.matches.count %> Total) </h5>

  <h5>
    <% if !@user.industry_interests.empty? %>
      Industry Interests: <% @user.industry_interests.each do |industry_interest| %>
        <%= industry_interest.industry.name %>
      <% end %>
    <% end %>

    <% if !@user.function_interests.empty? %>
      Function Interests: <% @user.function_interests.each do |function_interest| %>
        <%= function_interest.function.name %>
      <% end %>
    <% end %>
  </h5>

  <table class="table">
    <thead>
      <th>Potential Intro</th>
      <th>Past Intros</th>
      <th># Intros</th>
      <th>User Score</th>
      <th>Shared Industries</th>
      <th>Shared Functions</th>
      <th>Shared Skills</th>
      <th>Shared Connections</th>
      <th>Rating</th>
    </thead>
    <tbody>
      <% @potential_matches.each_with_index do |potential_match, index| %>
        <tr>
          <td><%= link_to potential_match.name, user_path(potential_match) %></td>
          <td><%= link_to 'Past Intros', admins_past_matches_path(potential_match) %></td>
          <td><%= @number_of_intros[index] %></td>
          <td><%= potential_match.score %></td>
          <td><%= @shared_industry_interests[index] %></td>
          <td><%= @shared_function_interests[index] %></td>
          <td><%= @shared_skills[index] %></td>
          <td><%= @shared_connections[index] %></td>
          <td><%= @rating[index] %></td>
          <td><%= button_to "Create Match", user_matches_path(@user, user_1: @user.id, user_2: potential_match.id), method: 'post', class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>