config/routes.rb
require 'sidekiq/web'

SwiftIntro::Application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect("/")
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'users#show'
  
  resources :users, except: [:index] do
    get 'matches/prior_matches', to: 'matches#prior_matches'
    put 'matches/:id/send_potential_match_email', to: 'matches#send_potential_match_email', as: 'send_potential_match_email'
    resources :matches do
      resources :messages, only: [:create]
    end
    get 'messages/inbox', to: 'messages#inbox', as: 'messages_inbox'
    get 'messages/sent', to: 'messages#sent', as: 'messages_sent'
    post 'messages/send_message', to: 'messages#send_message', as: 'send_message'
  end

  mount Sidekiq::Web, at: '/admins/sidekiq'

  get 'admins/requests'
  get 'admins/metrics'
  get 'admins/queue'
  get 'admins/:id/past_matches', to: 'admins#past_matches', as: 'admins_past_matches'

  get 'users/:id/invite', to: 'users#invite', as: 'user_invite'
  get 'users/:id/premium', to: 'users#premium', as: 'user_premium'
  get 'users/:id/settings', to: 'users#settings', as: 'user_settings'
  post 'users/:id/delete_account', to: 'users#delete_account', as: 'user_delete_account'

  resources :admins, only: [:index, :show]
  resources :dashboard, only: [:index]

  get '/contact', to: 'dashboard#contact', as: 'contact'
  get '/faq', to: 'dashboard#faq', as: 'faq'
  get '/privacy', to: 'dashboard#privacy', as: 'privacy'

  get '/terms', to: 'dashboard#terms', as: 'terms'

  get '/:ref', to: 'dashboard#index'
end

app/views/layouts/_contact_us.html.erb
<div class="contact">
  <div class="footer-subitem"><%= link_to "Home", root_path %></div>
  <div class="footer-subitem"><%= link_to "Blog", 'http://blog.swiftintro.com/', target: 'blank' %></div>
  <div class="footer-subitem"><%= link_to "FAQ", faq_path %></div>
  <div class="footer-subitem"><%= link_to "Contact", contact_path %></div>
  <div class="footer-subitem"><%= link_to "Privacy", privacy_path %></div>
  <div class="footer-subitem"><%= link_to "Terms", terms_path %></div> 
  <p>&copy; SwiftIntro 2014</p>

  <div class="social-share-buttons">
    <%= link_to "https://www.facebook.com/swiftintro", target: 'blank' do %>
      <i class="fa fa-facebook-square fa-2x"></i>
    <% end %>
    <%= link_to "https://twitter.com/SwiftIntro", target: 'blank' do %>
      <i class="fa fa-twitter-square fa-2x"></i>
    <% end %>
    <%= link_to "http://blog.swiftintro.com/", target: 'blank' do %>
      <i class="fa fa-tumblr-square fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <b><%= content_tag :div, msg, :id => "flash_#{name}" %></b>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49583938-1', 'swiftintro.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_message.html.erb
<div class = "new-message">
<%= form_for [@user, @match, @message] do |f| %>
    <%= f.label :Subject %>:
    <%= f.text_field :title, class: 'form-control' %><br />

    <%= f.label :Message %>:
    <%= f.text_area :body, class: 'form-control' %><br />
    
    <%= f.submit "Submit", class:"btn btn-primary" %>

  <% end %>
</div>

app/views/layouts/_messageresponse.html.erb
<div class = "new-message">
<%= form_for [@user, @message], :url => { :action => :send_message } do |f| %>
    <%= f.label :Subject %>:
    <%= f.text_field :title, class: 'form-control' %><br />

    <%= f.label :Message %>:
    <%= f.text_area :body, class: 'form-control', :rows=>5 %><br />
    
    <%= hidden_field_tag :message_id, "" %>
    
    <%= f.submit "Submit", class:"btn btn-primary" %>

  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#swiftintro-navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <div style="font-family: Lobster, cursive"><%= link_to "SwiftIntro", root_path, class:"navbar-brand" %></div>
    </div>
    <div class="navbar-collapse collapse" id="swiftintro-navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>

        <% if current_user.admin %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Index", admins_path %></li>
              <li><%= link_to "Queue", admins_queue_path %></li>
              <li><%= link_to 'Beta requests', admins_requests_path %></li>
              <li><%= link_to "Metrics", admins_metrics_path %></li>
              <li><%= link_to "Sidekiq", sidekiq_web_path %></li>
            </ul>
          </li>
        <% end %>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Inbox", user_messages_inbox_path(current_user) %></li>
            <li><%= link_to 'Sent', user_messages_sent_path(current_user) %></li>
          </ul>
        </li> -->

        <li><%= link_to "Invite", user_invite_path(current_user) %></li>
        <li><%= link_to "Premium", user_premium_path(current_user) %></li>

          <% if !current_user.matches.empty? && current_user.approved == "Yes" %>
            <% if current_user.matches.where(match_status: true).count >= 1 %>
              <li><%= link_to "Successful Intros", user_matches_prior_matches_path(current_user)%></li>
            <% end %>
            <li><%= link_to "Pending Intros", user_matches_path(current_user) %></li>
            <li><%= link_to "Current Intro", user_match_path(current_user, current_user.current_match) %></li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user)%></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li><%= link_to "Settings", user_settings_path(current_user)%></li>
              <li><%= link_to "Sign out", signout_path%></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_profile.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <div class="row center">
      <%= link_to @user.public_profile, target: 'blank' do %>
        <%= image_tag @user.image, size: "250x250", alt: 'Profile Picture', class:'profile-picture' %>
      <% end %>
    </div>
    <div class="row center">
      <h2><%= @user.name %></h2>
      <h4><%= @user.headline %></h4>
      <h4><%= @user.location.area %></h4>

      <% if @user.badge %>
        <%= image_tag 'premium_badge.png', size: '70x60' %>
      <% end %>

      <div class="linkedin-box">
        <h4>
          <%= link_to @user.public_profile, target: 'blank' do %>
            <%= image_tag 'https://static.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png', size: '30x22' %> View My Profile
          <% end %>
        </h4>

        <% if @user.total_connections && @user.total_connections > 4999 %>
          <h5>Total Connections: 5000+</h5>
        <% elsif @user.total_connections && @user.total_connections > 999 %>
          <h5>Total Connections: 1000+</h5>
        <% elsif @user.total_connections && @user.total_connections > 499 %>
          <h5>Total Connections: 500+</h5>
        <% elsif @user.total_connections && @user.total_connections > 100 %>
          <h5>Total Connections: <%= @user.total_connections %></h5>
        <% end %>

        <% if @match %>
          <%= render partial: 'matches/mutual_connections' %>
        <% end %>
      </div>
    
    </div>
  </div>

  <div class="col-md-6 col-md-offset-1">
    <div class="row">
      <div>
        <% if @user.summary && !@user.summary.empty? %>
          <h3>Professional Summary</h3>
          <p><%= @user.summary %></p>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div>
        <% if !@user.jobs.empty? %>
          <h3>Recent Experience</h3>
          <% @user.jobs.sort.take(5).each do |job| %>
            <p><%= job.company.name %>, <%= job.position.name %> </p>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div>
        <% if !@user.educations.empty? %>
          <h3>Education</h3>
          <% @user.educations.sort.each do |education| %>
            <p><%= education.school.name %>
            <% if education.subject && !education.subject.name.nil? %>
              <%= education.degree.name %> <%= education.subject.name %> <%= education.year %></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div>
        <% if !@user.skill_interests.empty? %>
          <h3 id="skills">Skills<%= link_to '▾' %></h3>
          <div id="skill-interests" style="display: none">
            <% @user.skill_interests.sort.each do |skill_interest| %>
              <%= skill_interest.skill.name %> |
            <% end %>
          </div>
        <% end %>
      </div>
    </div>  
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('#skills').click(function(event){
      event.preventDefault();
      $('#skill-interests').toggle();
    });
  }); 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  
  <title>SwiftIntro</title>

  <%= favicon_link_tag 'SwiftIntroThumbnail.ico' %>

  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>

  <meta property="og:title" content="SwiftIntro" />
  <meta property="og:site_name" content="SwiftIntro" />
  <meta property="og:url" content="https://www.swiftintro.com/" />
  <meta property="og:description" content="The smarter way to build your network" />
  <meta property="og:image" content="http://i.imgur.com/C82WLIN.png" />

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div id="wrap">
    <% if current_user %>
      <%= render partial: 'layouts/navbar' %>
    <% end %>

    <%= render partial: 'layouts/flash' %>

    <%= yield %>

    <div id="push">
    </div>
  </div>

  <%= render partial: 'layouts/contact_us' %>

  <%= render partial: 'layouts/footer' %>

</body>
</html>